on:
  schedule:
    - cron: '43 5 * * 1-5' # At 2:00 PM IST (08:00 UTC) on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{secrets.DATABASE.DATABASE_NAME}}
      TABLE_NAME: ${{secrets.DATABASE.TABLE_NAME}}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show environment
        run: |
          env | grep DATABASE_NAME
      - name: Show environment 1
        run: |
          env | grep TABLE_NAME
      - name: Create python script
        run: |
          cat > showenv.py <<'EOF'
          import os

          print(f'Email username is {os.environ.get("DATABASE_NAME", "<unknown")}')
          print(f'Email password is {os.environ.get("TABLE_NAME", "<unknown")}')
          EOF

      - name: Run python script
        run: |
          python execute.py
        