on:
  schedule:
    - cron: '30 16 * * *' # At 2:00 PM IST (08:00 UTC) on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      filename: ${{ vars.FILENAME }}
      sheetname: ${{ vars.SHEETNAME }}
      dict1: ${{ secrets.DICT1 }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show environment
        run: |
          env | grep filename
      - name: Show environment 1
        run: |
          env | grep sheetname
      - name: Show environment 2
        run: |
            env | grep dict1          
      - name: Create python script
        run: |
          cat > showenv.py <<'EOF'
          import os

          print(f'Email username is {os.environ.get("DATABASE_NAME", "<unknown")}')
          print(f'Email password is {os.environ.get("TABLE_NAME", "<unknown")}')
          EOF

      - name: Run python script
        run: |
          python database_cloud_v1.py
        env:
          filename: ${{ vars.FILENAME }}
          sheetname: ${{ vars.SHEETNAME }}
          dict1: ${{ secrets.dict1 }}
