on:
  schedule:
    - cron: '5 16 * * 1-5' # At 2:00 PM IST (08:00 UTC) on weekdays

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Read secrets from secrets.toml
        run: |
          # Parse secrets.toml and extract database_name and table_name
          # Replace the following line with actual code to read the secrets
          database_name=$(cat secrets.toml | grep 'database_name' | cut -d '=' -f 2 | tr -d ' \t\n')
          table_name=$(cat secrets.toml | grep 'table_name' | cut -d '=' -f 2 | tr -d ' \t\n')
      - name: Execute Python script
        run: python execute.py
        # Pass the extracted secrets as environment variables
        env:
          DATABASE_NAME: ${{ secrets['database']['database_name'] }}
          TABLE_NAME: ${{ secrets['database']['table_name'] }}
