on:
  schedule:
    - cron: '22 21 * * 1-5' # At 2:00 PM IST (08:00 UTC) on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      TABLE_NAME: ${{secrets.TABLE_NAME}}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show environment
        run: |
          env | grep DATABASE_NAME
      - name: Show environment 1
        run: |
          env | grep TABLE_NAME
      - name: Execute Python script
        run: python execute.py
        # Pass the extracted secrets as environment variables
        env:
          DATABASE_NAME: secrets.DATABASE_NAME
          TABLE_NAME: secrets.TABLE_NAME
